version: "3.8"

services:
  front:
    container_name: front
    build:
      context: ./.docker/front
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./front:/app:cached
    stdin_open: true
    tty: true
    depends_on:
      - nginx
  nginx:
    container_name: nginx
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./api:/app:cached
    tty: true
    depends_on:
      - api
  api:
    container_name: api
    build:
      context: ./.docker/api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app:cached
    tty: true
    environment:
      - APP_ENV=development
    depends_on:
      - db
  db:
    container_name: db
    build:
      context: ./.docker/db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: nogi_fil
      MYSQL_USER: nogi_fil
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - db-volume:/var/lib/mysql:cached
    platform: linux/amd64

volumes:
  db-volume:
